### ISSUE TITLE
LUA Error: Mod names are used as IDs and must therefore be unique.

### ISSUE THREAD

**Issue by Tga123** [DeadlyBossMods/DBM-RaidLeadTools#1]
1) `Message: ...nterface\AddOns\DBM-RaidLeadTools\Modules\BidBot.lua:1: DBM:NewMod(): Mod names are used as IDs and must therefore be unique.`
2) `Message: ...face\AddOns\DBM-RaidLeadTools\Modules\StandByBot.lua:1: DBM:NewMod(): Mod names are used as IDs and must therefore be unique.`
3) `Message: ...face\AddOns\DBM-RaidLeadTools\Modules\AutoInvite.lua:1: DBM:NewMod(): Mod names are used as IDs and must therefore be unique.`

**Comment by MysticalOS** [comment]
Sounds like @Developaws Did poor testing, cause that would have literally be found running the mod even once :D
